### ISSUE TITLE
Multiple sliders: dragging chances value of others

### ISSUE THREAD

**Issue by jorgevargas1989** [src-zone/material#2]
On chrome mobile, with multiple sliders stacked above one another, dragging one slider also changes the value of the other slider. To reproduce:

1. Open https://blox.src.zone/material#/directives/linear-progress
2. Unselect 'indeterminate' in the example
3. Drag the pin of the first slider
4. Drag the pin of the second slider

Action 4 changes the value of the first slider.

Seems to only affect mobile browsers. On desktop (with mouse) cold not reproduce.

**Comment by gjdev** [comment]
This is an upstream bug from MCW itself. See material-components/material-components-web#1192. MCW released a new version yesterday that fixes this. When we release a new version compatible with MCW v0.25.0 (expected next monday), this issue will be fixed.

**Comment by gjdev** [comment]
This is fixed in v0.6.0, because of the upstream fix in MCW 0.25.0.
