### ISSUE TITLE
Incorrect bundle sourcemaps for site debugging

### ISSUE THREAD

**Issue by jorgevargas1989** [src-zone/material#608]
When debugging the site, the sourcemaps for the @blox/material bundle point to the transpiled javascript, instead of the original typescript sources. (I.e. for mdc.button.directive.ts you will see javascript code in Chrome Devtools, instead of the typescript code).

This is probably a problem in the site/webpack.config.js, because testing in another project that depends on @blox/material does show the typescript sources correctly.

**Comment by gjdev** [comment]
Fixed in #614 by making source-map-loader process all javascript files before other loaders
