### ISSUE TITLE
How to handle a checkbox in a clickable ListItem

### ISSUE THREAD

**Issue by taxpayer** [src-zone/material#661]
Hello!

I have a list with clickable items. I want to have a checkbox before the items to select them but as I check the checkbox, the click event from the ListItem is fired. Any thoughts on how can I handle that?

Thanks for the great set of components.

**Comment by taxpayer** [comment]
Yes, you're right. In the meantime I did that and worked. I was coming back to write that but you were faster... ;-)

BTW, do you intend to implement a checkbox/selection functionality in the List component?

Thanks again.

**Comment by gjdev** [comment]
For styling purposes, you can embed your checkbox inside the list items in a span with the `mdcListItemGraphic` directive. There's also the `selected` property for styling a selected item.

Other than that, the only thing currently on the roadmap for the `mdcList` is keyboard support to conform to WAI-ARIA best practices for Listbox.
