### ISSUE TITLE
Not able to load MDCComponent in IE11

### ISSUE THREAD

**Issue by rojagadeesh** [src-zone/material#662]
I am using Blox material in my angular application.  I followed all the steps mentioned in IE11 guide (https://blox.src.zone/material/guides/ie11).  I'm still getting below error :

SCRIPT1002: Syntax Error
File: vendor.js, Line: 135186, Column: 1

In Vendor.js
class MDCComponent {  (Line 135186)

Please let me know if I'm missing something

**Comment by gjdev** [comment]
Can you check that the transpile script actually creates transpiled versions of your scripts, and that those are used by the bundle (e.g. your index.html)?

If you want me to take a look, please at least give the versions of angular and angular-cli you are using. Or even better, provide a small project that reproduces this.

**Comment by rojagadeesh** [comment]
My bad.  Not able to replicate the issue.
