### ISSUE TITLE
StackBlitz Demo Not Working

### ISSUE THREAD

**Issue by Rajdeep-Das** [src-zone/material#673]
Error in /turbo_modules/@angular/compiler@8.0.0/bundles/compiler.umd.js (26943:43)
this.getExtraNgModuleProviders is not a function

The above error occurred for every demo component.

![boxmaterial_error](https://user-images.githubusercontent.com/22764172/73445861-a9648200-4381-11ea-9700-f55e5e2369b2.JPG)

**Comment by gjdev** [comment]
Fixed by d8d0d04d85b7b21db28aac2b61be3e70001022bf
Will redeploy site shortly, so it is fixed online as well.
